// Code generated by sqlcodegen, DO NOT EDIT.

package sqlstructs

import "database/sql"

/*
	SELECT id FROM users LIMIT 5
*/
type X struct {
	Id sql.NullInt64 `db:"id" json:"id"`
}

/*
	SELECT firebase_auth_uid FROM users LIMIT 5
*/
type Foo struct {
	FirebaseAuthUid sql.NullString `db:"firebase_auth_uid" json:"firebase_auth_uid"`
}

/*
	SELECT *
	FROM
	users
	LIMIT 5
*/
type Bar struct {
	Id              sql.NullInt64  `db:"id" json:"id"`
	FirebaseAuthUid sql.NullString `db:"firebase_auth_uid" json:"firebase_auth_uid"`
}

/*
	SELECT users.*, title FROM users JOIN posts ON users.id = posts.id
*/
type JoinExample struct {
	Id              sql.NullInt64  `db:"id" json:"id"`
	FirebaseAuthUid sql.NullString `db:"firebase_auth_uid" json:"firebase_auth_uid"`
	Title           string         `db:"title" json:"title"`
}
